version: '3.8'

services:
  k-scan:
    build: .
    ports:
      - "8000:8000"
    environment:
      # Python Configuration
      - PYTHONDONTWRITEBYTECODE=1
      - PYTHONUNBUFFERED=1
      
      # Required: OpenAI API Configuration
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - OPENAI_MODEL=${OPENAI_MODEL:-gpt-4o}
      - OPENAI_MODEL_TEMPERATURE=${OPENAI_MODEL_TEMPERATURE:-0.1}
      
      # Optional: Browserless Configuration
      - BROWSERLESS_TOKEN=${BROWSERLESS_TOKEN:-}
      - BROWSERLESS_URL=${BROWSERLESS_URL:-https://chrome.browserless.io}
      
      # Application Configuration
      - APP_NAME=${APP_NAME:-K-Scan Security Audit System}
      - VERSION=${VERSION:-1.0.0}
      - DEBUG=${DEBUG:-false}
      
      # Database Configuration
      - DATABASE_URL=${DATABASE_URL}
      
      # API Configuration
      - API_HOST=${API_HOST:-0.0.0.0}
      - API_PORT=${API_PORT:-8000}
      - API_RELOAD=${API_RELOAD:-false}

      # Celery Configuration
      - CELERY_BROKER_URL=${CELERY_BROKER_URL:-redis://redis:6379/0}
      - CELERY_RESULT_BACKEND=${CELERY_RESULT_BACKEND:-redis://redis:6379/0}
    volumes:
      # Persist database and data files
      - k-scan-data:/app/data
      # Development: mount source code (comment out for production)
      - .:/app:ro
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - k-scan-network

  celery-worker:
    build: .
    command: celery -A src.celery worker -l info -P gevent
    environment:
      - PYTHONDONTWRITEBYTECODE=1
      - PYTHONUNBUFFERED=1
      - DATABASE_URL=${DATABASE_URL}
      - CELERY_BROKER_URL=${CELERY_BROKER_URL:-redis://redis:6379/0}
      - CELERY_RESULT_BACKEND=${CELERY_RESULT_BACKEND:-redis://redis:6379/0}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - BROWSERLESS_TOKEN=${BROWSERLESS_TOKEN:-}
    volumes:
      - .:/app
    depends_on:
      - k-scan
      - redis
    restart: unless-stopped
    networks:
      - k-scan-network

  celery-flower:
    image: mher/flower
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - FLOWER_PORT=5555
    ports:
      - "5555:5555"
    depends_on:
      - redis
    networks:
      - k-scan-network

  # Optional: Redis for caching (uncomment if needed)
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    restart: unless-stopped
    networks:
      - k-scan-network

  # Optional: PostgreSQL database (uncomment if moving from SQLite)
  # postgres:
  #   image: postgres:15-alpine
  #   environment:
  #     - POSTGRES_DB=k_scan
  #     - POSTGRES_USER=k_scan_user
  #     - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-secure_password_change_me}
  #   ports:
  #     - "5432:5432"
  #   volumes:
  #     - postgres-data:/var/lib/postgresql/data
  #   restart: unless-stopped
  #   networks:
  #     - k-scan-network

volumes:
  k-scan-data:
    driver: local
  redis-data:
    driver: local
  # postgres-data:
  #   driver: local

networks:
  k-scan-network:
    driver: bridge 